using System;

// This file represents the VSTO entry point for the Microsoft Project Add-in.
// In a real VSTO project, ThisAddIn inherits from
// Microsoft.Office.Tools.AddIn (generated by the VSTO designer).
//
// Build requirement: Visual Studio with Office/SharePoint development workload + MS Project.

namespace ScheduleSync.AddIn
{
    /// <summary>
    /// VSTO Add-in entry point for Microsoft Project.
    /// Manages add-in lifecycle (Startup/Shutdown) and provides access
    /// to the active Project application instance.
    /// </summary>
    /// <remarks>
    /// In the actual VSTO project this class is partial and extends the
    /// designer-generated ThisAddIn base. The code below shows the intended
    /// implementation; it will not compile without the VSTO project template.
    /// </remarks>
    public partial class ThisAddIn
    {
        // The VSTO template generates: internal Microsoft.Office.Interop.MSProject.Application Application { get; }

        private void ThisAddIn_Startup(object sender, EventArgs e)
        {
            // Add-in startup logic.
            // Initialize the MsProjectAdapter with the Application reference.
        }

        private void ThisAddIn_Shutdown(object sender, EventArgs e)
        {
            // Cleanup: close any open modeless windows, release COM objects.
        }

        #region VSTO generated code (placeholder)

        /// <summary>
        /// Required method for Designer support.
        /// </summary>
        private void InternalStartup()
        {
            // this.Startup += new EventHandler(ThisAddIn_Startup);
            // this.Shutdown += new EventHandler(ThisAddIn_Shutdown);
        }

        #endregion
    }
}
